import React, { useState } from 'react';
import { useApp } from '../../../contexts/AppContext';

type ReportKind = 'today' | 'month' | 'revenue' | 'expenses' | 'debts' | 'payments';

const REPORTS: Array<{ kind: ReportKind; labelKey: string; icon: React.ReactNode; tone: string }> = [
  {
    kind: 'today',
    labelKey: 'fin.reports.today',
    tone: 'bg-indigo-50 text-indigo-600 dark:bg-indigo-950/40 dark:text-indigo-300',
    icon: (
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.8} className="h-5 w-5">
        <rect x="3" y="4" width="18" height="18" rx="2" />
        <path strokeLinecap="round" strokeLinejoin="round" d="M16 2v4M8 2v4M3 10h18" />
      </svg>
    ),
  },
  {
    kind: 'month',
    labelKey: 'fin.reports.month',
    tone: 'bg-indigo-50 text-indigo-600 dark:bg-indigo-950/40 dark:text-indigo-300',
    icon: (
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.8} className="h-5 w-5">
        <rect x="3" y="4" width="18" height="18" rx="2" />
        <path strokeLinecap="round" strokeLinejoin="round" d="M16 2v4M8 2v4M3 10h18" />
      </svg>
    ),
  },
  {
    kind: 'revenue',
    labelKey: 'fin.reports.revenue',
    tone: 'bg-emerald-50 text-emerald-600 dark:bg-emerald-950/40 dark:text-emerald-300',
    icon: (
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.8} className="h-5 w-5">
        <path strokeLinecap="round" strokeLinejoin="round" d="M3 17l6-6 4 4 8-8M14 7h7v7" />
      </svg>
    ),
  },
  {
    kind: 'expenses',
    labelKey: 'fin.reports.expenses',
    tone: 'bg-rose-50 text-rose-600 dark:bg-rose-950/40 dark:text-rose-300',
    icon: (
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.8} className="h-5 w-5">
        <path strokeLinecap="round" strokeLinejoin="round" d="M3 7l6 6 4-4 8 8M14 17h7v-7" />
      </svg>
    ),
  },
  {
    kind: 'debts',
    labelKey: 'fin.reports.debts',
    tone: 'bg-amber-50 text-amber-600 dark:bg-amber-950/40 dark:text-amber-300',
    icon: (
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.8} className="h-5 w-5">
        <circle cx="12" cy="12" r="10" />
        <path strokeLinecap="round" strokeLinejoin="round" d="M12 8v4M12 16h.01" />
      </svg>
    ),
  },
  {
    kind: 'payments',
    labelKey: 'fin.reports.payments',
    tone: 'bg-violet-50 text-violet-600 dark:bg-violet-950/40 dark:text-violet-300',
    icon: (
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.8} className="h-5 w-5">
        <path strokeLinecap="round" strokeLinejoin="round" d="M12 1v22M17 5H9.5a3.5 3.5 0 000 7h5a3.5 3.5 0 010 7H6" />
      </svg>
    ),
  },
];

/**
 * Reports tab — six download cards, one per report kind. Each click hits
 * GET /finance/reports/download/{kind} which streams a PDF generated by
 * FinanceReportsController.
 */
export const FinanceReportsTab: React.FC = () => {
  const { t, token } = useApp();
  const [downloading, setDownloading] = useState<ReportKind | null>(null);
  const [error, setError] = useState<string | null>(null);

  const download = async (kind: ReportKind) => {
    if (!token) return;
    setDownloading(kind);
    setError(null);
    try {
      const res = await fetch(`/api/finance/reports/download/${kind}`, {
        headers: { Authorization: `Bearer ${token}`, Accept: 'application/pdf' },
      });
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `finance-${kind}-${new Date().toISOString().slice(0, 10)}.pdf`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
    } catch (e) {
      setError(e instanceof Error ? e.message : t('fin.reports.errorGeneric'));
    } finally {
      setDownloading(null);
    }
  };

  return (
    <div className="space-y-4">
      {error && (
        <div className="rounded-lg border border-rose-200 bg-rose-50 px-3 py-2 text-xs text-rose-700 dark:border-rose-900 dark:bg-rose-950/40 dark:text-rose-300">
          {error}
        </div>
      )}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {REPORTS.map(({ kind, labelKey, icon, tone }) => (
          <div
            key={kind}
            className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-900"
          >
            <div className="flex items-start justify-between gap-3">
              <h3 className="text-sm font-semibold text-slate-900 dark:text-slate-100">
                {t(labelKey as Parameters<typeof t>[0])}
              </h3>
              <div className={`flex h-10 w-10 items-center justify-center rounded-xl ${tone}`}>{icon}</div>
            </div>
            <button
              type="button"
              onClick={() => void download(kind)}
              disabled={downloading === kind}
              className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-lg bg-linear-to-r from-indigo-600 to-violet-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:from-indigo-500 hover:to-violet-500 disabled:opacity-50"
            >
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} className="h-4 w-4">
                <path strokeLinecap="round" strokeLinejoin="round" d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M7 10l5 5 5-5M12 15V3" />
              </svg>
              {downloading === kind ? t('fin.reports.downloading') : t('fin.reports.download')}
            </button>
          </div>
        ))}
      </div>
    </div>
  );
};
